options:
  snap_channel:
    default: "stable"
    type: string
    description: |
        This option controlls channel name.
        Supported values are: "stable", "candidate", "beta" and "edge"
  ssl_ca:
    default: ""
    type: string
    description: |
      TLS CA certficate, to be added as OS_CACERT
  os-credentials:
    default: ""
    type: string
    description: |
      YAML string with admin user to use to query openstack APIs, e.g.
      "{ username: $OS_USERNAME, password: $OS_PASSWORD,
         tenant_name: $OS_TENANT_NAME, region_name: $OS_REGION_NAME,
         auth_url: '$OS_AUTH_URL' }"
  extra-nrpe-args:
    type: string
    default: ""
    description: |
      Additional arguments to set for the check_http Nagios nrpe check.  E.g.
      if you wish to increase timeouts, set to '-w 20 -c 30'.
  port:
    type: int
    default: 9180
    description: |
      Port where the exporter listens
  network:
    type: boolean
    default: True
    description: |
      Network service exporter
  compute:
    type: boolean
    default: True
    description: |
      Compute service exporter
  image:
    type: boolean
    default: True
    description: |
      Image service exporter
  volume:
    type: boolean
    default: False
    description: |
      Volume service exporter
  identity:
    type: boolean
    default: True
    description: |
      Identity service exporter
  object-store:
    type: boolean
    default: False
    description: |
      Object store service exporter
  load-balancer:
    type: boolean
    default: False
    description: |
      Load balancer service exporter
  container-infra:
    type: boolean
    default: False
    description: |
      Container infra service exporter
  dns:
    type: boolean
    default: False
    description: |
      DNS service exporter
  baremetal:
    type: boolean
    default: False
    description: |
      Baremetal service exporter
  gnocchi:
    type: boolean
    default: False
    description: |
      Gnocchi service exporter
  disable_metrics:
    type: string
    default: ""
    description: |
      Disable metrics named in comma separated string
  disable_slow_metrics:
    type: boolean
    default: False
    description: |
      Disable slow metrics for performance reasons
  collect_metric_time:
    type: boolean
    default: True
    description: |
      Export time spent collecting each metric
  prefix:
    default: "openstack"
    type: string
    description: |
      Prometheus prefix for metrics
